function generateADR(
    scenario,
    recommendation
){


    const winner =
        recommendation.winner;


    const alternatives =
        recommendation.alternatives;



    let adr = "";



    adr +=
`
==================================================
ARCHITECTURE DECISION RECORD
==================================================


Decision
--------------------------------------------------

Adopt ${winner.name}


Category:
${winner.category}



Context
--------------------------------------------------

${scenario.summary}



Business / Engineering Drivers
--------------------------------------------------

`;



    scenario.priorities.forEach(
        item => {

            adr +=
            `✓ ${item}\n`;

        }
    );



    adr +=
`

Why This Architecture
--------------------------------------------------

`;



    winner.strengths.forEach(
        item => {

            adr +=
            `✓ ${item}\n`;

        }
    );





    adr +=
`

Architecture Tradeoffs Accepted
--------------------------------------------------

`;



    winner.weaknesses.forEach(
        item => {

            adr +=
            `⚠ ${item}\n`;

        }
    );





    adr +=
`

Alternatives Considered
==================================================

`;




    alternatives.forEach(
        architecture => {


            adr +=
`
${architecture.name}

Why it was not selected:
`;



            architecture.weaknesses
                .slice(0,3)
                .forEach(
                    item => {

                        adr +=
                        `- ${item}\n`;

                    }
                );


            adr += "\n";

        }

    );






    adr +=
`
Operational Considerations
==================================================

Recommended implementation considerations:

`;



    if(
        winner.id === "kafka"
    ){

        adr +=
`
- Partition strategy
- Consumer lag monitoring
- Schema evolution strategy
- Cluster capacity planning
`;

    }



    else if(
        winner.id === "sqs"
    ){

        adr +=
`
- Dead letter queue strategy
- Retry policies
- Visibility timeout tuning
- Idempotent consumers
`;

    }



    else if(
        winner.id === "eventbridge"
    ){

        adr +=
`
- Event schema governance
- Event routing rules
- Integration monitoring
`;

    }



    else {


        adr +=
`
- Capacity planning
- Monitoring strategy
- Failure recovery procedures
`;

    }





    adr +=
`

==================================================
Generated by Architecture Tradeoff Explorer
==================================================
`;



    return adr;


}