const OPERATIONAL_NOTES = {
  kafka: `
- Partition strategy
- Consumer lag monitoring
- Schema evolution strategy
- Cluster capacity planning
`,
  kinesis: `
- Shard count and capacity planning
- Retention window configuration
- Enhanced fan-out consumer pattern
- Lambda / Flink integration points
`,
  sqs: `
- Dead letter queue strategy
- Retry policies
- Visibility timeout tuning
- Idempotent consumers
`,
  eventbridge: `
- Event schema governance
- Event routing rules
- Integration monitoring
`,
  lambda: `
- Cold start mitigation
- Timeout and memory tuning
- Reserved concurrency
- Observability and tracing
`,
  apigateway: `
- Throttling and quota policies
- Authentication and authorization
- Request validation
- Usage plans and monitoring
`,
  ecs: `
- Fargate vs. EC2 placement
- Service auto scaling
- Image registry and CI pipeline
- Capacity planning
`,
  rosa: `
- Node pool sizing and scaling
- Cluster upgrade strategy
- Role-based access control
- Backup and disaster recovery
`,
  pubsub: `
- Topic and subscription design
- Exactly-once and ordering key strategy
- Retention and seek configuration
- Cross-region replication
`,
  default: `
- Capacity planning
- Monitoring strategy
- Failure recovery procedures
`,
};

function generateADR(scenario, recommendation) {
  const winner = recommendation.winner;
  const alternatives = recommendation.alternatives;
  let adr = "";
  adr += `
==================================================
ARCHITECTURE DECISION RECORD
==================================================


Decision
--------------------------------------------------

Adopt ${winner.name}


Category:
${winner.category}



Context
--------------------------------------------------

${scenario.summary}



Business / Engineering Drivers
--------------------------------------------------

`;

  scenario.priorities.forEach((item) => {
    adr += `✓ ${item}\n`;
  });
  adr += `

Why This Architecture
--------------------------------------------------

`;

  winner.strengths.forEach((item) => {
    adr += `✓ ${item}\n`;
  });
  adr += `

Architecture Tradeoffs Accepted
--------------------------------------------------

`;

  winner.weaknesses.forEach((item) => {
    adr += `⚠ ${item}\n`;
  });
  adr += `

Alternatives Considered
==================================================

`;

  alternatives.forEach((architecture) => {
    adr += `
${architecture.name}

Why it was not selected:
`;

    architecture.weaknesses.slice(0, 3).forEach((item) => {
      adr += `- ${item}\n`;
    });
    adr += "\n";
  });
  adr += `
Operational Considerations
==================================================

Recommended implementation considerations:

`;
  adr += OPERATIONAL_NOTES[winner.id] || OPERATIONAL_NOTES.default;
  adr += `

==================================================
Generated by Architecture Tradeoff Explorer
==================================================
`;
  return adr;
}
