name: Check and deploy to GitHub Pages
on: push

jobs:
  check-and-deploy:
    name: Check content and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Deploy to GitHub Pages
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        cname: wahab2.com